on:
  pull_request_target:
    types: [opened]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    name: Add preview footer to PR
    steps:
    - name: Add preview footer to PR
      uses: devindford/Append_PR_Comment@v1.1.2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        body-template: |
          ---
          See preview on Cloudflare Pages: https://preview-${{ github.event.number }}.staging-quiltmc-org.pages.dev
        body-update-action: 'suffix'
