on:
  workflow_call:
    inputs:
      branch:
        required: false
        default: ${{ github.ref_name }}
        type: string

jobs:
  publish:
    name: "Publish to Cloudflare Pages"
    runs-on: ubuntu-latest
    outputs:
      deployment-url: ${{ steps.cloudflare-publish.outputs.url }}
    permissions:
      contents: read
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
    steps:
      - name: Download Website HTML
        uses: actions/download-artifact@v4
        with:
          name: html
          path: dist
      - name: Download Website Functions
        uses: actions/download-artifact@v4
        with:
          name: functions
          path: functions
      
      # The following hack is required because Cloudflare can't compile the workeers in the functions/ directory seperately from deploying, so it needs the packages they use in order to compile them at deployment time, but installing *everything* in package.json would be a waste. The build and publish steps can't go in the same job, because PR Previews have to build the site without publishing it (since they can't access secrets). Hopefully we can remove the need for this in the future by switching to Astro Actions, which should be compiled with the rest of the site.
      - name: Install packages required by functions
        run: npm install xml-js semver-sort string_decoder buffer
      - name: Publish to Cloudflare Pages
        id: cloudflare-publish # This step needs an ID because its outputs may be needed in subsequent jobs.
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ env.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ env.CLOUDFLARE_ACCOUNT_ID }}
          projectName: quiltmc-org
          directory: dist
          branch: ${{ inputs.branch }}
